### ISSUE TITLE
Quality Development checklist

### ISSUE THREAD

**Issue by Vulcalien** [Vulcalien/unict-qd-sudoku#13]
- [x] Inviare email di presentazione (fatto il 2023-11-27)
- [x] Creare issue GitHub in `qd-projects`: [issue](https://github.com/UNICT-Quality-Development/qd-projects/issues/40)
- [x] Creare una repository GitHub
- [x] Utilizzare git ed i [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Utilizzare l’auto-formatter black (opzionale)
- [x] Creare una pipeline per il progetto
- [x] Pull Request revisionate da almeno un membro del team
- [x] Usare il linguaggio di programmazione Python
- [x] Code coverage almeno del 75%
- [ ] Inviare email di consegna
